apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app-frontend
spec:
  replicas: 2  # Número de réplicas do pod
  selector:
    matchLabels:
      app: meu-app-frontend
  template:
    metadata:
      labels:
        app: meu-app-frontend
    spec:
      containers:
      - name: meu-app-frontend
        image: meu-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80